# Deloppgave 4: Studiedesign

<!-- Part 4: Study designs -->


## Introduksjon
Styrketrening er den viktigste intervensjonen for å øke muskelmasse blant mennesker. Teorien sier at volumet med styrketrening spiller en signifikant rolle i kroniske muskulære endringer og tilpasninger som for eksempel økt styrke og økt muskelmasse [@kraemer_fundamentals_2004]. Ivaretagelse av muskelstyrke og muskelmasse er viktig for alle. For populasjonen i sin helhet er det viktig med tilstrekkelig styrke for å kunne utføre daglige oppgaver uten utfordringer. Å være fysisk sterk har også flere positive helseeffekter, det er til og med god evidens på at økt muskulær helse gir lavere dødelighet [@ruiz_association_2008].

Det er tidligere foreslått at styrketrening med høyt treningsvolum, med moderat til høy intensitet og korte hvilepauser gir først og fremst muskelbyggende effekt i form av hypertrofi, deretter økt utvikling av styrke [@baechle_essentials_2008]. På den andre siden vil et lavere treningsvolum, men tyngre vekter/økt intensitet og lengre hvilepauser primært være et program for å øke muskelstyrke først og fremst. Dette er i tråd med hvordan kroppsbyggere trener i faser der de ønsker å maksimere muligheten for hypertrofi og i studier som rapporterer om økt hypertrofi i tråd med at treningsvolumet øker [@schoenfeld_dose-response_2017].

I denne oppgaven skal det undersøkes hvordan ulike mengder og ulike intensiteter med styrketrening påvirker utviklingen av styrke og muskelvekst hos trente individer. Det er valgt ut fem artikler for gjennomgang av disse undersøkelsene [@brigatto_high_2022; @mangine_effect_2015; @mangine_resistance_2016; @schoenfeld_effects_2015; @schoenfeld_resistance_2019]. For å finne frem til nettopp disse 5 studiene ble det brukt et generelt litteratursøk etter originale studier rettet mot treningsvolum og intensitet, begrenset til de siste 10 årene. 2 av studiene undersøkte lavt treningsvolum versus høyt treningsvolum, på ulike intensitetsområder [@schoenfeld_effects_2015; @schoenfeld_resistance_2019]. I de to neste artiklene undersøkte forfatterne [@mangine_effect_2015; @mangine_resistance_2016] effekten av et visst treningsvolum versus treningsintensitet i to ulike studier, med litt forskjellige målemetoder. I det siste av fem studier så @brigatto_high_2022 på effekten av ulike treningsvolum for å undersøke nærmere dose-respons forholdet til styrketrening. Oppgaven inkluderer en vurdering av studiedesign, likheter og ulikheter i studiene og styrker og svakheter med de forskjellige studiene.

## Metode
 @schoenfeld_effects_2015 brukte et randomisert studiedesign der 24 menn ble paret etter styrke ved pre-test for deretter å bli tilfeldig plassert i en av to grupper. De hadde en gjennomsnittsalder på 23 år, hadde ingen nåværende muskel- og skjelettskader og var «rene utøvere». Alle deltagerne var erfarne i styrketrening, det vil si at de har trent minimum 3 økter i uken det siste året og regelmessig trent knebøy og benkpress. Studien bestod av en gruppe som trente på lav intensitet (30-50% av 1RM) til utmattelse og den andre gruppen trente 8-12 repetisjoner på høy intensitet (70-80% av 1RM). Begge gruppene trente samme øvelser, men med ulike vekter og repetisjoner. Tester ble gjennomført før og etter (pre og post) intervensjonsperioden (8 uker) med måling av maksimal styrke i form av 1RM i Knebøy og benkpress og måling av muskulær utholdenhet i benkpress ved maks antall repetisjoner utført på 50% av 1RM. Det ble også målt tykkelse av muskulatur ved å bruke ultralyd. Tykkelsen ble målt på triceps, biceps og quadriceps. En paret t-test ble brukt for å undersøke forskjeller fra før og etter intervensjon. Multippel regresjonsanalyse med mål post-intervensjon som avhengig variabel og pre-test verdiene som kovariater ble brukt for å vurdere forskjeller mellom gruppene. Forutsetningene i regresjonsanalysene ble kontrollert. Signifikansnivået ble satt til P < 0.05.
 
@mangine_resistance_2016 brukte et randomisert studiedesign der 33 fysisk aktive menn ble rekruttert for å sammenligne to ulike intervensjoner. Alle deltagerne med erfaring i styrketrening tilsvarende minimum 2 år (gjennomsnitt på 5.7 års erfaring), uten noen nåværende muskel- og skjelettskader. Intervensjonen var et 8 ukers styrketreningsprogram etter et 2 ukers styrketreningsprogram likt for alle deltagerne. Gruppene ble delt i to grupper der en gruppe gjennomførte trening på høy intensitet og lavt treningsvolum, og den andre gruppen gjennomførte trening på høyt volum og moderat intensitet. Utover dette har ikke forfatterne utdypet metoden de brukte for å rekruttere deltagere. Deltagerne ble testet i 1RM i knebøy og benkpress, med måling av hastigheten på stangen i den konsentriske fasen. Nøyaktige samme maksimale vekt ble brukt på pre- og post-tester, slik at forfatterne kunne utforske om hastigheten endret seg på samme vekt etter intervensjonsperioden. Kraftproduksjon ved isometrisk kontraksjon i andredraget (midten av lårene, i markløft/frivending) ble også målt ved hjelp av en kraftplate og en fastspent stang. Dataen ble analysen med kovariansanalyse (ANCOVA) etter intervensjonsperioden. Dataen fra pre-test ble brukt som kovarians. En paret t-test ble brukt for å undersøke om det var en signifikant endring fra pre- til post-test. Forskjellen mellom gruppene ble analysert ved å regne ut effektstørrelsen. Signifikansnivået ble satt til P < 0.05.

@brigatto_high_2022 brukte et randomisert studiedesign der 27 mannlige deltagerne ble paret etter styrkenivå og deretter tilfeldig plassert i en av tre like store grupper. Der gruppene gjennomførte henholdsvis, 16, 24 og 32 ukentlig sett med trening per muskelgruppe. Deltagerne hadde minimum 1 års erfaring med styrketrening tre ganger per uke og ble rekruttert gjennom universitetets treningsstudio. Det ble på forhånd gjort beregninger på utvalgsstørrelsen med basert på en pilotstudie, med en effektstørrelse på 0.75, alfanivå på P < 0.05 og statistisk styrke på 0.80. Deltagerne ble testet med 1RM i knebøy og benkpress og ved å måle muskeltykkelse ved bruk av ultralyd på bicpes, triceps og vastus lateralis. Det var en utdannet tekniker som utførte alle ultralydene. Forfatterne bekreftet normaliteten og homogeniteten til variansene ved å bruke Shapiro-Wilk og Levene tester. En variansanalyse med gjentatte mål (ANOVA) ble brukt for å sammenligne 1RM og hypertrofi før og etter intervensjonen på tvers av studiegruppene.  

@schoenfeld_resistance_2019 brukte et randomisert studiedesign med 45 mannlige deltagere som meldte seg frivillig. Deltagerne var studenter på et universitet som var erfarne innen styrketrening med gjennomsnittlig erfaring på 4.4 år. Det ble på forhånd gjort beregninger på utvalgsstørrelsen med en effektstørrelse på 0.25, med en alpha-verdi på 0.05 og en statistisk styrke på 0.80. Disse beregningene identifiserte at studien hadde behov for minimum 36 deltagere. Øvrige deltagere var rekruttert i tilfelle noen trakk seg underveis. Deltagerne ble deretter tilfeldig delt in i 3 like store grupper der en gruppe gjennomførte 1 sett per øvelse per økt, en gruppe trente 3 sett per øvelse per økt og den siste gruppen trente 5 sett per øvelse per økt. Det ble mål muskeltykkelse med ultralyd på biceps, triceps og quadriceps av en enkelt utdannet teknikker på alle deltagerne. Maksimal styrke ble testet med 1RM i knebøy og benkpress og muskulær utholdenhet i benkpress ble testet med 50% av 1RM til utmattelse. Statistiske analyser ble gjennomført ved å bruke både frekventistisk og Bayesiansk tilnærming. Den første brukte en ANCOVA på endringen fra pre-test til post-test, med separate grupper som faktor og med verdiene fra pre-test som kovarians. I den Bayesianske tilnærmingen ble det brukt en JZS Factor ANCOVA med standardiserte skalaer. Signifikansnivået ble satt til P < 0.05.

@mangine_effect_2015 brukte et randomisert studiedesign med 33 fysisk aktive menn. Minimum 2 års erfaring med regelmessig styrketrening var et av inklusjonskriteriene (samme studiepopulasjon som Magine et al. 2016). Alle deltagerne gjennomførte samme treningsprogram på 2 uker før de ble tilfeldig delt inn en av 2 like store grupper. Den ene gruppen trente med et høyt volum på 10-12 repetisjoner på 70% av 1RM, mens den andre gruppen trente på en høy intensitet på 3-5 repetisjoner på 90% av 1RM. Begge gruppene trente i 8 uker. Deltagerne ble testet og målt med maksimal styrke med 1RM i knebøy og benkpress, ultralydmålinger på triceps, quadriceps og pectoralis major for å måte muskeltykkelse og DXA skann for å måle kroppsmasse og endringer. Alle DXA undersøkelser ble utført av samme utdannede radiograf.  Blodprøver ble tatt ved 4 tidspunkt på pre- og post-testing, med gjentakende tidspunkt på dagen. Dataen ble analysen med kovariansanalyse (ANCOVA) etter intervensjonsperioden. Dataen fra pre-test ble brukt som kovarians. En paret t-test ble brukt for å undersøke om det var en signifikant endring fra pre- til post-test. Forskjellen mellom gruppene ble analysert ved å regne ut effektstørrelsen. Signifikansnivået ble satt til P < 0.05.

## Diskusjon
Alle studiene gjennomførte et randomisert studiedesign, men @brigatto_high_2022 skriver sin studie som en randomisert longitudinell studie. Ettersom ingen av studiene har en kontrollgruppe, men sammenligner to eller flere ulike intervensjoner er det heller ingen av forfatterne som hevder at de gjennomfører en randomisert kontrollstudie. Alle studiene er gjennomført med en 8 ukers treningsperiode. Antall forsøkspersoner er fordelt fra 18 til 45 forsøkspersoner. Alle forsøkspersoner er unge menn i aldersgruppen 18-35 år og alle er kjent med styrketrening, med litt ulike definisjoner på antall år for å regnes som kjent med styrketrening. Alle studiene beskriver hvordan forsøkspersonene er rekruttert, @mangine_resistance_2016 har en begrenset beskrivelse av rekruttering av forsøkspersoner. Tre av fem studier er helt randomiserte og de siste studiene bruker stratifisert blokkert randomisering  [@hulley_designing_2013].

Alle fem studier bruker 1RM målinger i knebøy og markløft, noe som bidrar til en enkel sammenligning av forskjellige studier til tross for ulike spørsmål mål med studiene. Utover det varierer målemetoden litt fra studie til studie. Det er ikke i noen av studiene nevnt noe om teknikker som gjennomfører ultralyd- eller andre målinger er blindet. Det er også relativt store variasjoner i hvordan målinger med ultralyd er gjennomført. Liggende og stående målinger er ikke nødvendigvis sammenlignbare, og det ville vært en fordel i denne analysen at alle målingene ble gjennomført i samme utgangsstilling. Øvelsene som brukes i de forskjellige studiene samsvarer i all hovedsak godt i de forskjellige studiene, men kun en eller to øvelser som varierer fra studie til studie. Felles for studiene er inklusjon av typiske øvelser som brukes i styrketreningsprogram og av kroppsbyggere [@baechle_essentials_2008].

To av de fem studiene beskriver at de på forhånd har beregnet utvalgsstørrelsen som er nødvendig for å trekke konklusjoner, men de øvrige tre studiene beskriver ikke dette i sin statistikk. De forskjellige studiene bruker ANCOVA der data samlet fra pre-test ble brukt som kovarians. @brigatto_high_2022 bruker ANOVA for å sammenligne 1RM og hypertrofi før og etter intervensjonen på tvers av studiegruppene. Tre av fem studier beskriver at de også brukte en paret t-test for å undersøke om det var en signifikant endring fra pre- til post-test innad de forskjellige gruppene.

Alle studiene svarer på egen problemstilling gjennom analyse av endringer i pre og post-verdier, både innad i egne grupper og på tvers av ulike grupper. Alle studier, bortsett fra @mangine_effect_2015 går grundig gjennom studiene sine begrensninger, sistnevnte beskriver ikke begrensninger studiet kan ha hatt. Alle artikler er spesifikke på sine konklusjoner til sin populasjon (unge, trente menn), men ikke alle går dypere gjennom mulig inferens mot øvrig populasjon.

## Konklusjon
Alle studiene adresserte hypotesen deres i konklusjonen og diskuterer resultatene som førte til dette. @schoenfeld_effects_2015, @schoenfeld_resistance_2019 og @brigatto_high_2022 foreslår alle videre forskning innenfor teamet. Alle spesifiserer også behovet for studier på treningsvolum og effekt av styrketrening mot en bredere befolkning, for eksempel kvinner og eldre. @mangine_effect_2015 og @mangine_resistance_2016 er to studier som kommer fra nøyaktig samme populasjon og lik intervensjon, men med ulike mål og hypoteser. Ingen av de studiene kommer med forslag til videre forskning og har heller ikke et stort søkelys på inferens i sin artikkel. Videre studier undersøke og sammenligne effekten unge, trente menn har på styrketrening med eldre og/eller kvinner. Dette kan i fremtiden gi oss mer kunnskap om treningsprogrammering og spesifikk inkludering av trening på en gitt intensitet eller et gitt treningsvolum. 
